packages:
  - frontend
  - applemusic-like-lyrics/packages/*

catalog:
  '@biomejs/biome': ^2.4.8
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@ungap/structured-clone': ^1.3.0
  '@vitejs/plugin-react': ^6.0.1
  classnames: ^2.5.1
  framer-motion: ^12.38.0
  react: ^19.2.4
  react-dom: ^19.2.4
  sharp: ^0.34.5
  typedoc: ^0.28.17
  typedoc-plugin-markdown: ^4.11.0
  typescript: ^5.9.3
  vite: ^8.0.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-svgr: ^4.5.0
  vite-plugin-wasm: ^3.6.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

overrides:
  '@applemusic-like-lyrics/core': link:./applemusic-like-lyrics/packages/core
  '@applemusic-like-lyrics/fft': link:./applemusic-like-lyrics/packages/fft
  '@applemusic-like-lyrics/lyric': link:./applemusic-like-lyrics/packages/lyric
  '@applemusic-like-lyrics/player': link:./applemusic-like-lyrics/packages/player
  '@applemusic-like-lyrics/player-core': link:./applemusic-like-lyrics/packages/player-core
  '@applemusic-like-lyrics/react': link:./applemusic-like-lyrics/packages/react
  '@applemusic-like-lyrics/react-full': link:./applemusic-like-lyrics/packages/react-full
  '@applemusic-like-lyrics/skia-player': link:./applemusic-like-lyrics/packages/skia-player
  '@applemusic-like-lyrics/ttml': link:./applemusic-like-lyrics/packages/ttml
  '@applemusic-like-lyrics/vue': link:./applemusic-like-lyrics/packages/vue
  '@applemusic-like-lyrics/ws-protocol': link:./applemusic-like-lyrics/packages/ws-protocol
